// const colors = [
//   "#FFFFFF",
//   "#000000",
//   "#FF0000",
//   "#00FF00",
//   "#0000FF",
//   "#FFFF00",
//   "#FF00FF",
//   "#00FFFF",
//   "#C0C0C0",
//   "#808080",
//   "#800000",
//   "#808000",
//   "#008000",
//   "#800080",
//   "#008080",
//   "#FFA500",
//   "#A52A2A",
//   "#DEB887",
//   "#5F9EA0",
//   "#7FFF00",
//   "#D2691E",
//   "#FF7F50",
//   "#6495ED",
//   "#DC143C",
//   "#00FFFF",
//   "#8A2BE2",
//   "#FFD700",
//   "#D8BFD8",
//   "#FF6347",
//   "#40E0D0",
//   "#EE82EE",
//   "#F5DEB3",
//   "#F0E68C",
//   "#ADFF2F",
//   "#FFDAB9",
//   "#CD5C5C",
//   "#4B0082",
//   "#FFFFF0",
//   "#F0FFF0",
//   "#FF69B4",
//   "#CD853F",
//   "#FF4500",
//   "#DA70D6",
//   "#EEE8AA",
//   "#98FB98",
//   "#AFEEEE",
//   "#DB7093",
//   "#FFEFD5",
//   "#FFDAB9",
//   "#B0E0E6",
// ];
//array of color objects, including hexadecimal value and color name.
const colors = [
  { hex: "#FFFFFF", name: "White" },
  { hex: "#000000", name: "Black" },
  { hex: "#FF0000", name: "Red" },
  { hex: "#00FF00", name: "Lime" },
  { hex: "#0000FF", name: "Blue" },
  { hex: "#FFFF00", name: "Yellow" },
  { hex: "#FF00FF", name: "Magenta" },
  { hex: "#00FFFF", name: "Aqua" },
  { hex: "#C0C0C0", name: "Silver" },
  { hex: "#808080", name: "Gray" },
  { hex: "#800000", name: "Maroon" },
  { hex: "#808000", name: "Olive" },
  { hex: "#008000", name: "Green" },
  { hex: "#800080", name: "Purple" },
  { hex: "#008080", name: "Teal" },
  { hex: "#FFA500", name: "Orange" },
  { hex: "#A52A2A", name: "Brown" },
  { hex: "#DEB887", name: "Burly Wood" },
  { hex: "#5F9EA0", name: "Cadet Blue" },
  { hex: "#7FFF00", name: "Chartreuse" },
  { hex: "#D2691E", name: "Chocolate" },
  { hex: "#FF7F50", name: "Coral" },
  { hex: "#6495ED", name: "Corn flower Blue" },
  { hex: "#DC143C", name: "Crimson" },
  { hex: "#00FFFF", name: "Cyan" },
  { hex: "#8A2BE2", name: "Blue Violet" },
  { hex: "#FFD700", name: "Gold" },
  { hex: "#D8BFD8", name: "Thistle" },
  { hex: "#FF6347", name: "Tomato" },
  { hex: "#40E0D0", name: "Turquoise" },
  { hex: "#EE82EE", name: "Violet" },
  { hex: "#F5DEB3", name: "Wheat" },
  { hex: "#F0E68C", name: "Khaki" },
  { hex: "#ADFF2F", name: "Green Yellow" },
  { hex: "#FFDAB9", name: "Peach Puff" },
  { hex: "#CD5C5C", name: "Indian Red" },
  { hex: "#4B0082", name: "Indigo" },
  { hex: "#FFFFF0", name: "Ivory" },
  { hex: "#F0FFF0", name: "Honey dew" },
  { hex: "#FF69B4", name: "Hot Pink" },
  { hex: "#CD853F", name: "Peru" },
  { hex: "#FF4500", name: "Orange Red" },
  { hex: "#DA70D6", name: "Orchid" },
  { hex: "#EEE8AA", name: "Pale Golden Rod" },
  { hex: "#98FB98", name: "Pale Green" },
  { hex: "#AFEEEE", name: "Pale Turquoise" },
  { hex: "#DB7093", name: "Pale VioletRed" },
  { hex: "#FFEFD5", name: "Papaya Whip" },
  { hex: "#FFDAB9", name: "Peach Puff" },
  { hex: "#B0E0E6", name: "Powder Blue" },
];
const btn = document.getElementById("btn");
const color = document.querySelector(".color");
//when clicked
btn.addEventListener("click", function () {

  const randomNumber = getRandomNumber();
  console.log(randomNumber);
  document.body.style.backgroundColor = colors[randomNumber].hex;
  color.textContent = colors[randomNumber].name;
});
//get random number between 0 - colors.length;
//this makes the colors dynamic.
function getRandomNumber() {
  return Math.floor(Math.random() * colors.length);
}
